[package]
name = "dns_message"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.1.4"
rand = "0.8.5"
trust-dns-client = { version = "0.22.0", default-features = false }
